name: Dependency Scan

"on":
  pull_request:

permissions: {}

jobs:
  dependency-scan:
    uses: tempoxyz/gh-actions/.github/workflows/dependency-scan.yml@5840979a7c849cbe541c67431ec7315cd6396e3b # 2026-09-25T08-14-04Z-5840979a
    permissions:
      contents: read
      id-token: write
