name: Scan GitHub Actions

"on":
  pull_request:

permissions: {}

jobs:
  scan:
    name: Scan GitHub Actions
    uses: tempoxyz/gh-actions/.github/workflows/scan-github-actions.yml@5840979a7c849cbe541c67431ec7315cd6396e3b # 2026-09-25T08-14-04Z-5840979a
    permissions:
      actions: read
      contents: read
      id-token: write
